### ISSUE TITLE
Trying to run pod install and I get an error for iOSMath?

### ISSUE THREAD

**Issue by zacharisharris** [kostub/MathSolver#1]
Hello there, I am trying to run MathSolver as well as MathEditor but I get an error on both, when I am trying to run pod install. Can you help me run it?

Thank you very much in advance.

**Comment by kostub** [comment]
What is the error that you get? I can run `pod install` just fine.

**Comment by zacharisharris** [comment]
Yeah, sorry for that. I was trying to run it on macOS Sierra and I had compatibility issues. I have successfully installed all the pods but I have another problem now. I and trying to build the workspace and while it builds, it doesn't run. Why is that? Tried relaunching Xcode to no avail.
